# Generated by Django 5.1.6 on 2025-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_habit_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
