# Generated by Django 5.1.6 on 2025-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_habit_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
