# Generated by Django 5.1.6 on 2025-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_habit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(default='No description', max_length=200),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
