# Generated by Django 5.1.6 on 2025-03-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_habit_description_alter_habit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(default='enter description here', max_length=200),
        ),
    ]
