# Generated by Django 5.1.6 on 2025-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_habit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(default='enter description here', max_length=100),
        ),
    ]
