# Generated by Django 5.1.6 on 2025-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_habit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='name',
        ),
    ]
